import React from 'react'
import ToolTip from './ToolTip';

export default function Summary({summary}) {
  const paragraph = "Generated by an AI model using related posts. Content may not always be accurate or up to date."
  return (
    <div className="flex flex-col flex-start border border-[#D4D4D4] rounded-md mt-5 md:mt-15 text-left p-4 gap-y-2 w-full lg:w-1/2">
        <div className="border-b-1 border-[#D4D4D4] pb-2">
          <div className="flex flex-row gap-x-2 items-center justify-between">
            <h3>Summary</h3>
            <ToolTip paragraph={paragraph}/>
          </div>
        </div>
        
          {summary ? (
            <div className="flex flex-wrap p-2">{summary}</div>
          ) : (
            <div className="flex flex-wrap justify-center items-center leading-80">No data</div>
          )}
        
    </div>
  );
}