name: Trigger Disaster Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # runs every day at 8:00 AM UTC
  workflow_dispatch:     # allows manual triggering

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger pipeline via POST request
        run: |
          curl -X POST ${{ secrets.TRIGGER_PIPELINE_URL }}
